import { Trip, Itinerary, DayPlan, Activity, AlternativeActivity, WeatherInfo } from './types';

// ================================================================
// Seed Data — Sample trips & destinations for demo
// ================================================================

export const SAMPLE_DESTINATIONS = [
  'Tokyo, Japan', 'Paris, France', 'New York, USA', 'Bali, Indonesia',
  'Rome, Italy', 'London, UK', 'Singapore', 'Dubai, UAE',
  'Bangkok, Thailand', 'Sydney, Australia', 'Barcelona, Spain', 'Istanbul, Turkey',
];

export const INTEREST_OPTIONS = [
  'History & Culture', 'Food & Dining', 'Adventure & Outdoors', 'Art & Museums',
  'Shopping', 'Nightlife', 'Beaches', 'Nature & Wildlife', 'Architecture',
  'Local Experiences', 'Wellness & Spa', 'Photography', 'Sports', 'Music & Events',
];

export const TRAVEL_STYLES_META = {
  adventure: { label: 'Adventure', icon: '🏔️', color: 'emerald' },
  luxury: { label: 'Luxury', icon: '✨', color: 'amber' },
  budget: { label: 'Budget', icon: '💰', color: 'blue' },
  cultural: { label: 'Cultural', icon: '🏛️', color: 'purple' },
  family: { label: 'Family', icon: '👨‍👩‍👧‍👦', color: 'orange' },
  romantic: { label: 'Romantic', icon: '💕', color: 'pink' },
  business: { label: 'Business', icon: '💼', color: 'slate' },
};

// ----------------------------------------------------------------
// Tokyo Sample Trip (pre-generated for instant demo)
// ----------------------------------------------------------------

export const TOKYO_SAMPLE_TRIP: Trip = {
  id: 'trip_tokyo_demo',
  userId: 'user_demo',
  status: 'active',
  coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  intent: {
    id: 'intent_tokyo',
    destination: 'Tokyo, Japan',
    startDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    endDate: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0],
    budget: 1500,
    currency: 'USD',
    groupSize: 2,
    travelStyle: ['cultural', 'adventure'],
    pace: 'moderate',
    interests: ['History & Culture', 'Food & Dining', 'Art & Museums', 'Local Experiences'],
    dietaryRestrictions: [],
    mobilityNeeds: '',
    visaConstraints: [],
    naturalLanguageInput: '3-day trip to Tokyo for 2 people under $1500 focused on culture and food',
    createdAt: new Date().toISOString(),
    userId: 'user_demo',
  },
  itinerary: {
    id: 'itin_tokyo',
    tripId: 'trip_tokyo_demo',
    version: 1,
    totalEstimatedCost: 1240,
    budgetRemaining: 260,
    highlights: [
      'Explore ancient Asakusa & Senso-ji Temple at sunrise',
      'Immersive teamLab Borderless digital art experience',
      'Authentic ramen & sushi in Shibuya',
      'Panoramic views from Tokyo Skytree',
    ],
    generatedAt: new Date().toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    status: 'active',
    optimizationScore: 87,
    adaptationLog: [
      {
        id: 'adapt_1',
        timestamp: new Date().toISOString(),
        trigger: 'weather',
        description: 'Light rain expected on Day 2 afternoon. Moved outdoor Meiji Shrine visit to morning and added indoor teamLab experience in the afternoon.',
        changesApplied: ['Swapped Meiji Shrine to morning slot', 'Added teamLab Planets as afternoon activity'],
        impact: 'minor',
      },
    ],
    days: [
      {
        date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
        dayNumber: 1,
        theme: 'Ancient Tokyo — Temples, Shrines & Traditional Food',
        summary: 'Start your Tokyo journey in the historic Asakusa district, explore the iconic Senso-ji Temple, and end with an izakaya dinner.',
        totalCost: 180,
        totalDistance: 12.4,
        totalTravelTime: 85,
        weatherForecast: {
          condition: 'Partly Cloudy',
          temperatureHigh: 22,
          temperatureLow: 15,
          precipitation: 10,
          humidity: 65,
          icon: '⛅',
        },
        notes: 'Wear comfortable walking shoes. Most temples open from 6 AM.',
        activities: [
          {
            id: 'act_1_1',
            name: 'Senso-ji Temple & Nakamise Shopping Street',
            description: "Tokyo's oldest temple dating to 628 AD. Arrive early to beat crowds and photograph the iconic Kaminarimon gate. Browse 200m of traditional craft shops along Nakamise-dori.",
            category: 'attraction',
            timeSlot: 'morning',
            startTime: '08:00',
            endTime: '10:30',
            durationMinutes: 150,
            estimatedCost: 0,
            currency: 'USD',
            location: {
              name: 'Senso-ji Temple',
              address: '2-3-1 Asakusa, Taito City, Tokyo',
              coordinates: { lat: 35.7148, lng: 139.7967 },
            },
            rating: 4.8,
            confidenceScore: 0.96,
            tags: ['Free', 'Historic', 'Photography', 'Cultural'],
            reasonIncluded: "A must-visit landmark perfectly matching your cultural interests. Morning visit avoids peak crowds and provides the best photography light.",
            alternatives: [
              {
                id: 'alt_1',
                name: 'Ueno Park & Museums',
                description: 'Large park with multiple world-class museums including the Tokyo National Museum.',
                estimatedCost: 15,
                durationMinutes: 180,
                reasonAlternative: 'Great if you prefer a more art-focused morning.',
                confidenceScore: 0.82,
              },
            ],
            imageUrl: 'https://images.unsplash.com/photo-1570459027562-4a916cc6113f?w=600&q=80',
          },
          {
            id: 'act_1_2',
            name: 'Tsukiji Outer Market Breakfast',
            description: 'World-famous fish market with dozens of street food stalls. Try fresh tuna sashimi, tamagoyaki (egg rolls), and Japanese breakfast bowls.',
            category: 'restaurant',
            timeSlot: 'morning',
            startTime: '10:45',
            endTime: '12:00',
            durationMinutes: 75,
            estimatedCost: 25,
            currency: 'USD',
            location: {
              name: 'Tsukiji Outer Market',
              address: '4 Chome-16-2 Tsukiji, Chuo City, Tokyo',
              coordinates: { lat: 35.6654, lng: 139.7707 },
            },
            distanceFromPrevious: 4.2,
            travelTimeFromPrevious: 22,
            transportMode: 'public-transit',
            rating: 4.6,
            confidenceScore: 0.91,
            tags: ['Food', 'Seafood', 'Authentic', 'Budget-Friendly'],
            reasonIncluded: 'Your food & dining interest is a top priority. Tsukiji is the definitive Tokyo food experience — fresh, affordable, and culturally rich.',
            alternatives: [
              {
                id: 'alt_2',
                name: 'Harajuku Omotesando Brunch',
                description: 'Trendy cafés and international dining in Tokyos fashion district.',
                estimatedCost: 35,
                durationMinutes: 60,
                reasonAlternative: 'Better if you prefer modern café culture over traditional seafood.',
                confidenceScore: 0.78,
              },
            ],
            imageUrl: 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=600&q=80',
          },
          {
            id: 'act_1_3',
            name: 'Tokyo National Museum',
            description: 'Japan\'s oldest and largest museum with over 110,000 items showcasing Japanese art, history, and culture from prehistoric to modern times.',
            category: 'attraction',
            timeSlot: 'afternoon',
            startTime: '13:00',
            endTime: '16:00',
            durationMinutes: 180,
            estimatedCost: 12,
            currency: 'USD',
            location: {
              name: 'Tokyo National Museum',
              address: '13-9 Uenokoen, Taito City, Tokyo',
              coordinates: { lat: 35.7189, lng: 139.7762 },
            },
            distanceFromPrevious: 3.1,
            travelTimeFromPrevious: 18,
            transportMode: 'public-transit',
            rating: 4.7,
            confidenceScore: 0.89,
            tags: ['Museum', 'Art', 'History', 'Cultural'],
            reasonIncluded: 'Perfectly aligned with your history & culture interests. The museum houses treasures spanning 10,000 years of Japanese civilization.',
            alternatives: [],
            imageUrl: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
          },
          {
            id: 'act_1_4',
            name: 'Akihabara Electric Town Exploration',
            description: "Tokyo's iconic electronics and anime district. Explore multi-story game centers, anime merchandise stores, and unique Japanese tech culture.",
            category: 'experience',
            timeSlot: 'afternoon',
            startTime: '16:30',
            endTime: '18:30',
            durationMinutes: 120,
            estimatedCost: 40,
            currency: 'USD',
            location: {
              name: 'Akihabara',
              address: 'Akihabara, Taito City, Tokyo',
              coordinates: { lat: 35.7023, lng: 139.7745 },
            },
            distanceFromPrevious: 2.8,
            travelTimeFromPrevious: 12,
            transportMode: 'walking',
            rating: 4.5,
            confidenceScore: 0.83,
            tags: ['Pop Culture', 'Shopping', 'Tech', 'Unique'],
            reasonIncluded: 'Provides a fascinating contrast to traditional Tokyo. Local Experiences is one of your top interests — Akihabara is unlike anywhere else on earth.',
            alternatives: [],
            imageUrl: 'https://images.unsplash.com/photo-1548438294-1ad5d5f4f063?w=600&q=80',
          },
          {
            id: 'act_1_5',
            name: 'Shinjuku Izakaya Dinner',
            description: "Authentic Japanese pub-style dinner in Shinjuku's Memory Lane (Omoide Yokocho). Yakitori, ramen, sake, and the real local bar scene under red lanterns.",
            category: 'restaurant',
            timeSlot: 'evening',
            startTime: '19:30',
            endTime: '21:30',
            durationMinutes: 120,
            estimatedCost: 45,
            currency: 'USD',
            location: {
              name: "Omoide Yokocho, Shinjuku",
              address: '1-2-11 Nishishinjuku, Shinjuku City, Tokyo',
              coordinates: { lat: 35.6905, lng: 139.6990 },
            },
            distanceFromPrevious: 5.5,
            travelTimeFromPrevious: 20,
            transportMode: 'public-transit',
            rating: 4.8,
            confidenceScore: 0.94,
            tags: ['Dinner', 'Authentic', 'Local', 'Nightlife'],
            reasonIncluded: 'Highly rated for couples seeking authentic local dining. Ranked top-3 dinner experience in Tokyo for cultural immersion.',
            alternatives: [],
          },
        ],
      },
      {
        date: new Date(Date.now() + 8 * 86400000).toISOString().split('T')[0],
        dayNumber: 2,
        theme: 'Modern Tokyo — Art, Innovation & City Heights',
        summary: 'Explore Harajuku and Meiji Shrine in the morning, dive into digital art at teamLab, then ascend Tokyo Skytree for breathtaking night views.',
        totalCost: 145,
        totalDistance: 18.7,
        totalTravelTime: 110,
        weatherForecast: {
          condition: 'Light Rain',
          temperatureHigh: 19,
          temperatureLow: 14,
          precipitation: 65,
          humidity: 78,
          icon: '🌧️',
          advisory: '☔ Bring an umbrella. Afternoon outdoor activities have been moved indoors.',
        },
        notes: 'Rain advisory: outdoor activities scheduled for morning. Afternoon is fully indoor.',
        activities: [
          {
            id: 'act_2_1',
            name: 'Meiji Jingu Shrine',
            description: 'Serene Shinto shrine dedicated to Emperor Meiji, set in 170 acres of forested land. Walk the torii-lined path for a peaceful morning ritual.',
            category: 'attraction',
            timeSlot: 'morning',
            startTime: '08:30',
            endTime: '10:00',
            durationMinutes: 90,
            estimatedCost: 0,
            currency: 'USD',
            location: {
              name: 'Meiji Jingu',
              address: '1-1 Yoyogikamizonocho, Shibuya City, Tokyo',
              coordinates: { lat: 35.6763, lng: 139.6993 },
            },
            rating: 4.7,
            confidenceScore: 0.93,
            tags: ['Free', 'Nature', 'Spiritual', 'Historic'],
            reasonIncluded: 'Moved to morning to avoid afternoon rain. Provides peaceful contrast to the bustling city.',
            alternatives: [],
            imageUrl: 'https://images.unsplash.com/photo-1583430386015-3e5e7c5fde4b?w=600&q=80',
          },
          {
            id: 'act_2_2',
            name: 'teamLab Planets TOYOSU',
            description: 'Immersive digital art museum featuring walk-through infinity rooms, water gardens, and mind-bending light installations. One of Tokyo\'s most unique experiences.',
            category: 'experience',
            timeSlot: 'afternoon',
            startTime: '13:00',
            endTime: '16:00',
            durationMinutes: 180,
            estimatedCost: 32,
            currency: 'USD',
            location: {
              name: 'teamLab Planets TOYOSU',
              address: '6-1-16 Toyosu, Koto City, Tokyo',
              coordinates: { lat: 35.6466, lng: 139.7952 },
            },
            distanceFromPrevious: 12.3,
            travelTimeFromPrevious: 35,
            transportMode: 'public-transit',
            rating: 4.9,
            confidenceScore: 0.97,
            tags: ['Art', 'Technology', 'Indoor', 'Unique', 'Instagram'],
            reasonIncluded: '⚡ Re-planned: Added due to rain forecast. This indoor attraction perfectly replaces the originally planned outdoor park visit while aligning with your art & culture interests.',
            alternatives: [],
            imageUrl: 'https://images.unsplash.com/photo-1518655048521-f130df041f66?w=600&q=80',
          },
          {
            id: 'act_2_3',
            name: 'Tokyo Skytree Observation Deck',
            description: "The world's second-tallest structure. The Tembo Deck at 350m offers 360° panoramic views of Tokyo and Mt. Fuji on clear days. Night views are spectacular.",
            category: 'attraction',
            timeSlot: 'evening',
            startTime: '18:00',
            endTime: '20:00',
            durationMinutes: 120,
            estimatedCost: 25,
            currency: 'USD',
            location: {
              name: 'Tokyo Skytree',
              address: '1-1-2 Oshiage, Sumida City, Tokyo',
              coordinates: { lat: 35.7101, lng: 139.8107 },
            },
            distanceFromPrevious: 5.8,
            travelTimeFromPrevious: 22,
            transportMode: 'public-transit',
            rating: 4.6,
            confidenceScore: 0.88,
            tags: ['Views', 'Landmark', 'Photography', 'Must-See'],
            reasonIncluded: 'Top-rated evening activity. Night cityscape from 350m is a bucket-list Tokyo experience.',
            alternatives: [],
          },
        ],
      },
      {
        date: new Date(Date.now() + 9 * 86400000).toISOString().split('T')[0],
        dayNumber: 3,
        theme: 'Shibuya & Ginza — Urban Energy, Fashion & Farewell Dinner',
        summary: 'Experience the iconic Shibuya Crossing, explore Harajuku fashion, luxury shopping in Ginza, and a memorable farewell dinner.',
        totalCost: 200,
        totalDistance: 10.2,
        totalTravelTime: 65,
        weatherForecast: {
          condition: 'Sunny',
          temperatureHigh: 25,
          temperatureLow: 17,
          precipitation: 5,
          humidity: 55,
          icon: '☀️',
        },
        notes: 'Perfect weather for outdoor exploration. Great day for rooftop dining.',
        activities: [
          {
            id: 'act_3_1',
            name: 'Shibuya Crossing & Scramble Square',
            description: "Watch Tokyo's famous 3,000-person synchronized crossing from above at Starbucks or the Scramble Square observatory. The ultimate Tokyo urban spectacle.",
            category: 'attraction',
            timeSlot: 'morning',
            startTime: '09:00',
            endTime: '10:30',
            durationMinutes: 90,
            estimatedCost: 8,
            currency: 'USD',
            location: {
              name: 'Shibuya Crossing',
              address: '2 Chome-2-1 Dogenzaka, Shibuya City, Tokyo',
              coordinates: { lat: 35.6595, lng: 139.7004 },
            },
            rating: 4.8,
            confidenceScore: 0.95,
            tags: ['Iconic', 'Photography', 'Urban', 'Free'],
            reasonIncluded: "Shibuya Crossing is Tokyo's most recognizable landmark and an unmissable experience for any visitor.",
            alternatives: [],
            imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80',
          },
          {
            id: 'act_3_2',
            name: 'Harajuku & Takeshita Street',
            description: 'Colorful pedestrian shopping street famous for youth fashion, crepes, and Japanese pop culture. Walk tree-lined Omotesando boulevard for luxury brands.',
            category: 'shopping',
            timeSlot: 'morning',
            startTime: '11:00',
            endTime: '13:00',
            durationMinutes: 120,
            estimatedCost: 60,
            currency: 'USD',
            location: {
              name: 'Harajuku Takeshita Street',
              address: 'Takeshita-dori, Jingumae, Shibuya City, Tokyo',
              coordinates: { lat: 35.6710, lng: 139.7041 },
            },
            distanceFromPrevious: 1.1,
            travelTimeFromPrevious: 15,
            transportMode: 'walking',
            rating: 4.5,
            confidenceScore: 0.85,
            tags: ['Shopping', 'Fashion', 'Youth Culture', 'Fun'],
            reasonIncluded: 'High walkability score from Shibuya. Provides a fun, culturally unique experience aligned with your local experiences interest.',
            alternatives: [],
          },
          {
            id: 'act_3_3',
            name: 'Ginza Luxury & Rooftop Lounge',
            description: "Tokyo's premier upscale shopping district. Browse flagship stores of international luxury brands. Visit the Itoya stationery flagship and end at a rooftop bar.",
            category: 'experience',
            timeSlot: 'afternoon',
            startTime: '14:30',
            endTime: '17:30',
            durationMinutes: 180,
            estimatedCost: 40,
            currency: 'USD',
            location: {
              name: 'Ginza District',
              address: 'Ginza, Chuo City, Tokyo',
              coordinates: { lat: 35.6716, lng: 139.7650 },
            },
            distanceFromPrevious: 5.2,
            travelTimeFromPrevious: 18,
            transportMode: 'public-transit',
            rating: 4.6,
            confidenceScore: 0.87,
            tags: ['Luxury', 'Shopping', 'Architecture', 'Drinks'],
            reasonIncluded: 'Ginza offers world-class shopping and Tokyo\'s finest architecture. Budget allocated allows for comfortable browsing and a cocktail.',
            alternatives: [],
          },
          {
            id: 'act_3_4',
            name: 'Sukiyabashi Jiro Farewell Omakase',
            description: "World-famous sushi restaurant (made famous by Jiro Dreams of Sushi). Book the affordable lunch counter at the satellite location for the ultimate farewell meal.",
            category: 'restaurant',
            timeSlot: 'evening',
            startTime: '19:00',
            endTime: '21:00',
            durationMinutes: 120,
            estimatedCost: 90,
            currency: 'USD',
            location: {
              name: 'Ginza Sushi Restaurant',
              address: '4 Chome-2-15 Ginza, Chuo City, Tokyo',
              coordinates: { lat: 35.6712, lng: 139.7660 },
            },
            distanceFromPrevious: 0.5,
            travelTimeFromPrevious: 8,
            transportMode: 'walking',
            rating: 4.9,
            confidenceScore: 0.92,
            tags: ['Fine Dining', 'Sushi', 'Bucket List', 'Special'],
            reasonIncluded: "A perfect farewell dinner. Premium sushi in Ginza is Tokyo's quintessential dining experience. Within budget allocation for the final evening.",
            alternatives: [],
          },
        ],
      },
    ],
  },
};

// ----------------------------------------------------------------
// More sample trips for the dashboard
// ----------------------------------------------------------------

export const SAMPLE_TRIPS: Trip[] = [
  TOKYO_SAMPLE_TRIP,
  {
    id: 'trip_bali_demo',
    userId: 'user_demo',
    status: 'planning',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    intent: {
      id: 'intent_bali',
      destination: 'Bali, Indonesia',
      startDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
      endDate: new Date(Date.now() + 37 * 86400000).toISOString().split('T')[0],
      budget: 2000,
      currency: 'USD',
      groupSize: 2,
      travelStyle: ['adventure', 'romantic'],
      pace: 'relaxed',
      interests: ['Beaches', 'Wellness & Spa', 'Adventure & Outdoors'],
      dietaryRestrictions: ['vegetarian'],
      mobilityNeeds: '',
      visaConstraints: [],
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      userId: 'user_demo',
    },
  },
];

export const DEMO_CHAT_SUGGESTIONS = [
  "Make this trip cheaper",
  "Replace outdoor activities because it may rain",
  "Add more food experiences",
  "Move museum visit to tomorrow",
  "Add nightlife for the last evening",
  "Find vegetarian-friendly restaurants",
  "Is there anything we missed?",
  "Show hidden gems nearby",
];
